[package]
name = "rustperl"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.41", features = ["derive"] }
enum-as-inner = "0.6.1"
logos = "0.15.0"
rustyline = "16.0.0"
